spring.application.name=coachflow

spring.datasource.url=jdbc:postgresql://localhost:5432/coachflow
spring.datasource.username=coachflow_user
spring.datasource.password=coachflow_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.address=0.0.0.0
server.port=8080