export const EQUIPMENT_OPTIONS = [
    { value: 'BODYWEIGHT', label: 'Bodyweight' },
    { value: 'BARBELL', label: 'Barbell' },
    { value: 'DUMBBELL', label: 'Dumbbell' },
    { value: 'KETTLEBELL', label: 'Kettlebell' },
    { value: 'TRAP_BAR', label: 'Trap Bar' },
    { value: 'LANDMINE', label: 'Landmine' },
    { value: 'CABLE', label: 'Cable' },
    { value: 'SMITH_MACHINE', label: 'Smith Machine' },
    { value: 'MACHINE', label: 'Machine' },
    { value: 'RESISTANCE_BAND', label: 'Resistance Band' },
    { value: 'MEDICINE_BALL', label: 'Medicine Ball' },
    { value: 'BOSU_BALL', label: 'BOSU Ball' },
    { value: 'BENCH', label: 'Bench' },
    { value: 'BOX', label: 'Box' },
    { value: 'TRX', label: 'TRX / Suspension Trainer' },
    { value: 'PLATFORM', label: 'Platform' },
    { value: 'SLED', label: 'Sled' },
    { value: 'TREADMILL', label: 'Treadmill' },
    { value: 'BIKE', label: 'Bike' },
    { value: 'ROWER', label: 'Rower' },
    { value: 'ELLIPTICAL', label: 'Elliptical' },
    { value: 'STAIR_STEPPER', label: 'Stair Stepper' },
    { value: 'FOAM_ROLLER', label: 'Foam Roller' },
    { value: 'YOGA_MAT', label: 'Yoga Mat' },
];

export const MUSCLE_OPTIONS = [
    { value: 'CHEST', label: 'Chest' },
    { value: 'UPPER_CHEST', label: 'Upper Chest' },
    { value: 'LATS', label: 'Lats' },
    { value: 'TRAPS', label: 'Traps' },
    { value: 'LOWER_BACK', label: 'Lower Back' },
    { value: 'SHOULDERS', label: 'Shoulders' },
    { value: 'FRONT_DELTS', label: 'Front Delts' },
    { value: 'SIDE_DELTS', label: 'Side Delts' },
    { value: 'REAR_DELTS', label: 'Rear Delts' },
    { value: 'BICEPS', label: 'Biceps' },
    { value: 'TRICEPS', label: 'Triceps' },
    { value: 'FOREARMS', label: 'Forearms' },
    { value: 'CORE', label: 'Core' },
    { value: 'ABS', label: 'Abs' },
    { value: 'OBLIQUES', label: 'Obliques' },
    { value: 'LEGS', label: 'Legs' },
    { value: 'QUADS', label: 'Quads' },
    { value: 'HAMSTRINGS', label: 'Hamstrings' },
    { value: 'GLUTES', label: 'Glutes' },
    { value: 'CALVES', label: 'Calves' },
    { value: 'HIP_FLEXORS', label: 'Hip Flexors' },
    { value: 'ADDUCTORS', label: 'Adductors' },
    { value: 'ABDUCTORS', label: 'Abductors' },
    { value: 'FULL_BODY', label: 'Full Body' },
];


export const EXERCISE_DIFFICULTY_OPTIONS = [
    { value: 'BEGINNER', label: 'Beginner' },
    { value: 'INTERMEDIATE', label: 'Intermediate' },
    { value: 'ADVANCED', label: 'Advanced' },
];

export const EXERCISE_TAG_OPTIONS = [
    { value: 'STRENGTH', label: 'Strength' },
    { value: 'POWER', label: 'Power' },
    { value: 'CARDIO', label: 'Cardio' },
    { value: 'MOBILITY', label: 'Mobility' },
    { value: 'STRETCH', label: 'Stretch' },
    { value: 'BALANCE', label: 'Balance' },
    { value: 'STABILITY', label: 'Stability' },
    { value: 'PLYOMETRIC', label: 'Plyometric' },
    { value: 'SINGLE_LEG', label: 'Single Leg' },
    { value: 'SINGLE_ARM', label: 'Single Arm' },
    { value: 'OVERHEAD', label: 'Overhead' },
    { value: 'PUSH', label: 'Push' },
    { value: 'PULL', label: 'Pull' },
    { value: 'INCLINE', label: 'Incline' },
    { value: 'Decline', label: 'Decline' },
    { value: 'ASSESSMENT', label: 'Assessment' },
    { value: 'CONDITIONING', label: 'Conditioning' },
    { value: 'WARMUP', label: 'Warmup' },
    { value: 'COOLDOWN', label: 'Cooldown' },
    { value: 'REHAB', label: 'Rehab' },
];