export const MOBILE_BREAKPOINT = 768;

export const IntakeSteps = {
    BASIC_INFO: 'BASIC_INFO',
    PARQ: 'PARQ',
    GOALS: 'GOALS',
    ACTIVITY_HISTORY: 'ACTIVITY_HISTORY',
    MEDICAL: 'MEDICAL',
    LIFESTYLE: 'LIFESTYLE',
    TRAINING_PREFERENCES: 'TRAINING_PREFERENCES',
    COMPLETED: 'COMPLETED'
};